CREATE TABLE Spring23_S003_21_Employee
    (EMPLOYEE_ID NUMBER(3) CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
     EMPLOYEE_FIRST_NAME VARCHAR2(20),
     EMPLOYEE_LAST_NAME VARCHAR2(20),
     EMPLOYEE_POSITION VARCHAR2(30),
     EMPLOYEE_EMAIL VARCHAR(30),
     EMPLOYEE_WORK_LOCATION VARCHAR2(20),
     EMPLOYEE_PHONE_NUMBER NUMBER(10),
     EMPLOYEE_GENDER VARCHAR2(10),
     EMPLOYEE_START_DATE DATE,
     EMPLOYEE_END_DATE DATE,
     EMPLOYEE_SSN VARCHAR2(15),
     EMPLOYEE_DEPARTMENT VARCHAR2(30));
     
--
CREATE TABLE Spring23_S003_21_Region
    (REGION_ID NUMBER(3) CONSTRAINT PK_REGION PRIMARY KEY, 
    REGIONAL_MANAGER_ID CONSTRAINT FK_EMPLOYEE_ID_4 REFERENCES Spring23_S003_21_Employee, 
    REGION_NAME VARCHAR2(15));
    
--
CREATE TABLE Spring23_S003_21_Kitchen
    (KITCHEN_ID NUMBER(10) CONSTRAINT PK_KITCHEN PRIMARY KEY,
     PHONE_NUMBER NUMBER(15),
     EMAIL_ID VARCHAR2(30),
     MANAGER_ID CONSTRAINT FK_EMPLOYEE_ID REFERENCES Spring23_S003_21_Employee,
     KITCHEN_ZIPCODE NUMBER(10),
     KITCHEN_CITY VARCHAR2(15),
     KITCHEN_STATE VARCHAR(15),
     REGIONAL_MANAGER_ID CONSTRAINT FK_EMPLOYEE_5 REFERENCES Spring23_S003_21_Employee);
     
--
CREATE TABLE Spring23_S003_21_Menu
    (FOOD_ID NUMBER(5) CONSTRAINT PK_MENU PRIMARY KEY,
     ITEM_NAME VARCHAR2(30),
     ITEM_CATEGORY VARCHAR2(15),
     PRICE NUMBER(5));
     
--
CREATE TABLE Spring23_S003_21_Raw_materials
    (DISTRIBUTOR_ID NUMBER(3) CONSTRAINT PK_RAW_MATERIALS PRIMARY KEY,
     PURCHASE_DATE DATE,
     PRODUCT_NAME VARCHAR2(20),
     QUANTITY NUMBER(10),
     PRICE NUMBER(10));
     
--
CREATE TABLE Spring23_S003_21_Discount
    (DISCOUNT_ID NUMBER(5) CONSTRAINT PK_DISCOUNT PRIMARY KEY,
     DISCOUNT_TYPE VARCHAR2(30),
     START_TIME DATE,
     END_TIME DATE,
     DISOCUNT_PERCENTAGE NUMBER(5));
     
--
CREATE TABLE Spring23_S003_21_Customer
    (CUSTOMER_ID NUMBER(15) CONSTRAINT PK_CUSTOMER PRIMARY KEY,
     CUSTOMER_FIRST_NAME VARCHAR2(15),
     CUSTOMER_LAST_NAME VARCHAR2(15),
     CUSTOMER_PHONE_NUMBER NUMBER(15),
     CUSTOMER_EMAIL VARCHAR2(30),
     CUSTOMER_GENDER VARCHAR2(15),
     CUSTOMER_TYPE VARCHAR2(30),
     CUSTOMER_ZIPCODE NUMBER(10),
     CUSTOMER_CITY VARCHAR2(15),
     CUSTOMER_STATE VARCHAR2(15),
     DISCOUNT_ID CONSTRAINT FK_DISCOUNT REFERENCES Spring23_S003_21_Discount);
     
--

CREATE TABLE Spring23_S003_21_Order
    (ORDER_ID NUMBER(10) CONSTRAINT PK_ORDER PRIMARY KEY,
     FOOD_ID NUMBER(5) CONSTRAINT FK_MENU_4 REFERENCES Spring23_S003_21_Menu,
     QUANTITY NUMBER(5),
     PRICE NUMBER(5),
     KITCHEN_ID NUMBER(4) CONSTRAINT FK_KITCHEN_ID_3 REFERENCES Spring23_S003_21_Kitchen,
     CUSTOMER_RATING NUMBER(2),
     PICKUP_LOCATION VARCHAR2(15),
     ORDER_TIME TIMESTAMP(0),
     DELIVERY_LOCATION VARCHAR2(30),
     DELIVERY_TIME TIMESTAMP(0),
     DELIVERY_PERSON_ID NUMBER(3) CONSTRAINT FK_EMPLOYEE_ID_3 REFERENCES Spring23_S003_21_Employee,
     CUSTOMER_ID NUMBER(15) CONSTRAINT FK_CUSTOMER_ID_3 REFERENCES Spring23_S003_21_Customer);
     

--
CREATE TABLE Spring23_S003_21_Puracharing_raw_materials
    (DISTRIBUTOR_ID CONSTRAINT FK_RAW_MATERIALS REFERENCES Spring23_S003_21_Raw_materials,
     KITCHEN_ID CONSTRAINT FK_KITCHEN REFERENCES Spring23_S003_21_Kitchen);

--
CREATE TABLE Spring23_S003_21_Works_for_kitchen
    (EMPLOYEE_ID CONSTRAINT FK_EMPLOYEE_1 REFERENCES Spring23_S003_21_Employee,
     KITCHEN_ID CONSTRAINT FK_KITCHEN_1 REFERENCES Spring23_S003_21_Kitchen);

--
CREATE TABLE Spring23_S003_21_Displays_menu
    (KITCHEN_ID CONSTRAINT FK_KITCHEN_2 REFERENCES Spring23_S003_21_Kitchen,
     FOOD_ID CONSTRAINT FK_MENU_2 REFERENCES Spring23_S003_21_Menu,
     MENU_AVAILABILITY NUMBER(1));


